artifacts_base_dir: artifacts

# =============================================================================
# DATA CONFIGURATION
# =============================================================================
data:
  coins: [BTC, ETH, LTC, XRP, BNB, ADA, XLM, TRX, DOGE, DOT]  # Mix of high-volume and diverse crypto sectors
  target_coin: XRP
  interval: 1h
  default_start_date: 2018-05-05  # XRP prices start varying from 2018-05-04
  default_end_date: 2025-10-25
  data_dir: artifacts/step_01_download
  
  # Collection settings
  collection:
    batch_limit: 1000
    max_retries: 3
    retry_delay: 5
    request_timeout: 30
    rate_limit_delay: 0.2
    min_data_ratio: 0.95
    max_unchanged_threshold: 5


# =============================================================================
# TRAIN/VALIDATION SPLIT CONFIGURATION
# =============================================================================
split:
  train_ratio: 0.8
  temporal: true


# =============================================================================
# TOKENIZATION CONFIGURATION
# =============================================================================
tokenization:
  vocab_size: 79  # 21 data + 48 timestep + 10 coin tokens
  method: quantile  # Percentiles will be auto-generated at runtime
  data_bins: 21  # Number of quantization bins for data tokens (0-20)


# =============================================================================
# SEQUENCE CONFIGURATION
# =============================================================================
sequences:
  input_length: 24            # 24 hours (1 day) of historical context
  output_length: 1            # Single prediction (legacy, not used in decoder-only)
  num_channels: 19            # All indicators: price, volume + 17 technical indicators
  prediction_horizon: 1        # Predict 1 hour ahead (legacy, not used in decoder-only)
  use_special_tokens: true     # Use timestep and coin tokens
  flatten_sequence: true       # Flatten to 1D for GPT-style decoder
  sequence_stride: 24          # Slide by 24 timesteps (1 day, 50% overlap)


# =============================================================================
# MODEL ARCHITECTURE
# =============================================================================
model:
  version: v6  # Decoder-only GPT-style transformer
  vocab_size: 79  # 21 data + 48 timestep + 10 coin tokens
  num_classes: 79
  num_coins: 10
  
  # Architecture
  d_model: 256
  nhead: 8
  num_decoder_layers: 6  # Reduced from 8 for memory efficiency with long sequences
  dim_feedforward: 1024
  dropout: 0.4
  activation: gelu
  max_seq_len: 10000  # Max flattened sequence length


# =============================================================================
# TRAINING CONFIGURATION
# =============================================================================
training:
  device: cuda
  epochs: 50
  batch_size: 8               # Reduced for 24-hour window sequences with gradient checkpointing
  num_workers: 8
  pin_memory: true            # Pin memory for faster GPU transfer
  
  # Optimizer
  learning_rate: 0.00001
  weight_decay: 0.00005
  max_grad_norm: 0.5
  
  # Multi-task learning
  trading_loss_weight: 0.3  # Weight for trading signal loss vs next-token loss
  trading_class_weights: [5.0, 0.5, 5.0]  # Weights for BUY, HOLD, SELL (weight rare classes higher)
  
  # Regularization
  dropout: 0.3
  label_smoothing: 0.15
  ordinal_sigma: 3.0  # Adjusted for 21 classes
  
  # Learning rate schedule
  scheduler: warmup_cosine
  warmup_epochs: 5
  warmup_start_lr: 0.000001
  
  # Early stopping
  early_stopping:
    enabled: true
    patience: 30
    min_delta: 0.0001


# =============================================================================
# SPECIAL TOKENS CONFIGURATION
# =============================================================================
special_tokens:
  data_range: [0, 20]  # Data tokens (21 bins)
  timestep_range: [21, 68]  # [T0] to [T47] (48 timestep tokens)
  coin_range: [69, 78]  # [BTC] to [DOT] (10 coin tokens)
  coin_names: [BTC, ETH, LTC, XRP, BNB, ADA, XLM, TRX, DOGE, DOT]


# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: null
