artifacts_base_dir: artifacts

# =============================================================================
# DATA CONFIGURATION
# =============================================================================
data:
  coins: [BTC, ETH, LTC, XRP, BNB, ADA, XLM, TRX, DOGE, DOT]  # Mix of high-volume and diverse crypto sectors
  target_coin: XRP
  interval: 1h
  default_start_date: 2018-05-05  # XRP prices start varying from 2018-05-04
  default_end_date: 2025-10-25
  data_dir: artifacts/step_01_download
  
  # Collection settings
  collection:
    batch_limit: 1000
    max_retries: 3
    retry_delay: 5
    request_timeout: 30
    rate_limit_delay: 0.2
    min_data_ratio: 0.95
    max_unchanged_threshold: 5

# =============================================================================
# TRAIN/VALIDATION SPLIT CONFIGURATION
# =============================================================================
split:
  train_ratio: 0.8
  temporal: true

# =============================================================================
# TOKENIZATION CONFIGURATION
# =============================================================================
tokenization:
  vocab_size: 256
  method: quantile  # Percentiles will be auto-generated at runtime (0.4 to 99.6)

# =============================================================================
# SEQUENCE CONFIGURATION
# =============================================================================
sequences:
  input_length: 48            # 48 hours (2 days) of historical context
  output_length: 1            # Single prediction
  num_channels: 18            # 18 channels: price, volume + 16 technical indicators
  prediction_horizon: 1        # Predict 1 hour ahead

# =============================================================================
# MODEL ARCHITECTURE
# =============================================================================
model:
  vocab_size: 256
  num_classes: 256
  num_coins: 10
  binary_classification: false
  
  # Architecture
  d_model: 256
  nhead: 8
  num_encoder_layers: 3
  num_decoder_layers: 2
  dim_feedforward: 1024
  dropout: 0.2
  
  # Embeddings
  coin_embedding_dim: 16
  positional_encoding: sinusoidal
  max_seq_len: 1024
  
  # V4 Features
  multi_horizon_enabled: false
  btc_attention_enabled: true
  time_features_enabled: false

# =============================================================================
# TRAINING CONFIGURATION
# =============================================================================
training:
  device: cuda
  epochs: 50
  batch_size: 128
  num_workers: 0
  
  # Optimizer
  learning_rate: 0.0015
  weight_decay: 0.0001
  max_grad_norm: 1.0
  
  # Regularization
  dropout: 0.2
  label_smoothing: 0.01
  gaussian_noise: 0.05
  
  # Learning rate schedule
  scheduler: warmup_cosine
  warmup_epochs: 3
  warmup_start_lr: 0.00001
  
  # Early stopping
  early_stopping:
    enabled: true
    patience: 30
    min_delta: 0.0001
  
  # Loss function (precision-focused)
  loss_type: asymmetric
  buy_penalty: 10.0
  no_buy_penalty: 1.0
  use_class_weights: true

# =============================================================================
# INFERENCE CONFIGURATION
# =============================================================================
inference:
  target_signal_rate: 0.01
  calibration:
    mode: precision_at_most_rate
    min_signals: 10
    confidence_threshold: 0.8
    precision_target: 0.75

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: null
